version: '3.7'

services:
  api:
    image: '${API_IMAGE}'
    build:
      context: .
      target: '${API_BUILD_TARGET}'
    ports:
      - "8080:8080"
    volumes:
      - '.:/usr/src/api'
      - 'target:/usr/src/api/target'
    env_file:
      - '.env'

volumes:
  target:
