version: '3.7'

services:
  api:
    image: '${API_IMAGE}'
    build:
      context: .
      target: '${API_BUILD_TARGET}'
    ports:
      - "8080:8080"
    volumes:
      - '.:/usr/src/api'
      - 'target:/usr/src/api/target'
    env_file:
      - '.env'
    depends_on:
      - 'db'

  db:
    image: 'postgres:11.4-alpine'
    ports:
      - '5432:5432'
    volumes:
      - 'db:/var/lib/postgresql/data'
    env_file:
      - '.env'

volumes:
  target:
  db:
